version: '3.8'

services:
  pysrc:
    platform: linux/amd64
    build:
      context: ../
      dockerfile: pysrc/Dockerfile
    image: gcr.io/radiozilla-92c5f/radiozilla-pysrc:latest
  scraperjob:
    platform: linux/amd64
    build:
      context: ../
      dockerfile: scraperjob/Dockerfile
    environment:
      - NODE_ENV=development
      - DB_URL=postgresql+asyncpg://db_user:db_password@host.docker.internal:5432/db
    restart: unless-stopped
    networks:
      - radiozilla-network
    image: gcr.io/radiozilla-92c5f/radiozilla-scraperjob:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - pysrc

networks:
  radiozilla-network:
    driver: bridge
