# psql -h localhost -p 5432 -U user -d db

version: '3.8'

services:
  db:
    image: pgvector/pgvector:0.8.0-pg17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: