/* tslint:disable */
/* eslint-disable */
/**
 * apiservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface FADomainStats
 */
export interface FADomainStats {
    /**
     * 
     * @type {string}
     * @memberof FADomainStats
     */
    'domain': string;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof FADomainStats
     */
    'frequent_subpaths': { [key: string]: number; };
}
/**
 * 
 * @export
 * @interface FAFrontendAudio
 */
export interface FAFrontendAudio {
    /**
     * 
     * @type {string}
     * @memberof FAFrontendAudio
     */
    'normalized_url_hash': string;
    /**
     * 
     * @type {string}
     * @memberof FAFrontendAudio
     */
    'normalized_url': string;
    /**
     * 
     * @type {string}
     * @memberof FAFrontendAudio
     */
    'title': string | null;
    /**
     * 
     * @type {string}
     * @memberof FAFrontendAudio
     */
    'description': string | null;
    /**
     * 
     * @type {string}
     * @memberof FAFrontendAudio
     */
    'audio_text': string | null;
    /**
     * 
     * @type {string}
     * @memberof FAFrontendAudio
     */
    'image_url': string | null;
    /**
     * 
     * @type {string}
     * @memberof FAFrontendAudio
     */
    'audio_url': string | null;
    /**
     * 
     * @type {string}
     * @memberof FAFrontendAudio
     */
    'author_id': string | null;
    /**
     * 
     * @type {string}
     * @memberof FAFrontendAudio
     */
    'channel_id': string | null;
    /**
     * 
     * @type {string}
     * @memberof FAFrontendAudio
     */
    'published_at': string | null;
    /**
     * 
     * @type {string}
     * @memberof FAFrontendAudio
     */
    'uploaded_at': string | null;
    /**
     * 
     * @type {number}
     * @memberof FAFrontendAudio
     */
    'duration': number | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof FAFrontendAudio
     */
    'topics': Array<string> | null;
    /**
     * 
     * @type {number}
     * @memberof FAFrontendAudio
     */
    'similarity_score'?: number | null;
}
/**
 * 
 * @export
 * @interface FAFrontendAudioSearchResult
 */
export interface FAFrontendAudioSearchResult {
    /**
     * 
     * @type {string}
     * @memberof FAFrontendAudioSearchResult
     */
    'normalized_url_hash': string;
    /**
     * 
     * @type {number}
     * @memberof FAFrontendAudioSearchResult
     */
    'similarity_score': number;
}
/**
 * 
 * @export
 * @interface FAScraperStats
 */
export interface FAScraperStats {
    /**
     * 
     * @type {number}
     * @memberof FAScraperStats
     */
    'initiated_urls_count': number;
    /**
     * 
     * @type {number}
     * @memberof FAScraperStats
     */
    'requested_urls_count': number;
    /**
     * 
     * @type {number}
     * @memberof FAScraperStats
     */
    'completed_urls_count': number;
    /**
     * 
     * @type {{ [key: string]: FADomainStats; }}
     * @memberof FAScraperStats
     */
    'domain_stats': { [key: string]: FADomainStats; };
}
/**
 * 
 * @export
 * @interface FAWebPage
 */
export interface FAWebPage {
    /**
     * 
     * @type {string}
     * @memberof FAWebPage
     */
    'normalized_url_hash': string;
    /**
     * 
     * @type {string}
     * @memberof FAWebPage
     */
    'normalized_url': string;
    /**
     * 
     * @type {string}
     * @memberof FAWebPage
     */
    'url': string;
    /**
     * 
     * @type {number}
     * @memberof FAWebPage
     */
    'status_code': number;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof FAWebPage
     */
    'headers': { [key: string]: string; } | null;
    /**
     * 
     * @type {File}
     * @memberof FAWebPage
     */
    'content': File | null;
    /**
     * 
     * @type {string}
     * @memberof FAWebPage
     */
    'content_type': string | null;
    /**
     * 
     * @type {string}
     * @memberof FAWebPage
     */
    'content_charset': string | null;
    /**
     * 
     * @type {string}
     * @memberof FAWebPage
     */
    'metadata_title': string | null;
    /**
     * 
     * @type {string}
     * @memberof FAWebPage
     */
    'metadata_description': string | null;
    /**
     * 
     * @type {string}
     * @memberof FAWebPage
     */
    'metadata_image_url': string | null;
    /**
     * 
     * @type {string}
     * @memberof FAWebPage
     */
    'metadata_published_at': string | null;
    /**
     * 
     * @type {string}
     * @memberof FAWebPage
     */
    'canonical_url': string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof FAWebPage
     */
    'outgoing_urls': Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof FAWebPage
     */
    'visible_text': string | null;
    /**
     * 
     * @type {string}
     * @memberof FAWebPage
     */
    'sitemap_url': string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof FAWebPage
     */
    'robots_content': Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof FAWebPage
     */
    'text_chunks': Array<string> | null;
}
/**
 * 
 * @export
 * @interface FAWebPageSeed
 */
export interface FAWebPageSeed {
    /**
     * 
     * @type {string}
     * @memberof FAWebPageSeed
     */
    'normalized_url_hash': string;
    /**
     * 
     * @type {string}
     * @memberof FAWebPageSeed
     */
    'normalized_url': string;
    /**
     * 
     * @type {string}
     * @memberof FAWebPageSeed
     */
    'url': string;
    /**
     * 
     * @type {number}
     * @memberof FAWebPageSeed
     */
    'max_depth': number;
    /**
     * 
     * @type {Array<string>}
     * @memberof FAWebPageSeed
     */
    'url_patterns': Array<string> | null;
    /**
     * 
     * @type {boolean}
     * @memberof FAWebPageSeed
     */
    'use_headless_browser': boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof FAWebPageSeed
     */
    'allowed_domains': Array<string> | null;
}
/**
 * 
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
    /**
     * 
     * @type {Array<ValidationError>}
     * @memberof HTTPValidationError
     */
    'detail'?: Array<ValidationError>;
}
/**
 * 
 * @export
 * @interface ScraperRunRequest
 */
export interface ScraperRunRequest {
    /**
     * 
     * @type {string}
     * @memberof ScraperRunRequest
     */
    'url': string;
    /**
     * 
     * @type {number}
     * @memberof ScraperRunRequest
     */
    'max_depth': number;
    /**
     * 
     * @type {boolean}
     * @memberof ScraperRunRequest
     */
    'no_cache': boolean;
}
/**
 * 
 * @export
 * @interface SummarizerRunRequest
 */
export interface SummarizerRunRequest {
    /**
     * 
     * @type {string}
     * @memberof SummarizerRunRequest
     */
    'url': string;
}
/**
 * 
 * @export
 * @interface UpsertWebPageSeedRequest
 */
export interface UpsertWebPageSeedRequest {
    /**
     * 
     * @type {string}
     * @memberof UpsertWebPageSeedRequest
     */
    'normalized_url_hash': string;
    /**
     * 
     * @type {string}
     * @memberof UpsertWebPageSeedRequest
     */
    'normalized_url': string;
    /**
     * 
     * @type {string}
     * @memberof UpsertWebPageSeedRequest
     */
    'url': string;
    /**
     * 
     * @type {number}
     * @memberof UpsertWebPageSeedRequest
     */
    'max_depth': number;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpsertWebPageSeedRequest
     */
    'url_patterns': Array<string> | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpsertWebPageSeedRequest
     */
    'use_headless_browser': boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpsertWebPageSeedRequest
     */
    'allowed_domains': Array<string> | null;
}
/**
 * 
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
    /**
     * 
     * @type {Array<ValidationErrorLocInner>}
     * @memberof ValidationError
     */
    'loc': Array<ValidationErrorLocInner>;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'msg': string;
    /**
     * 
     * @type {string}
     * @memberof ValidationError
     */
    'type': string;
}
/**
 * 
 * @export
 * @interface ValidationErrorLocInner
 */
export interface ValidationErrorLocInner {
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Detailed health check endpoint
         * @summary Detailed Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        detailedHealthCheckApiV1HealthDetailedGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/health/detailed`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Frontend Audio For Url
         * @param {string} url 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        frontendAudioForUrlApiV1FrontendAudioForUrlPost: async (url: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'url' is not null or undefined
            assertParamExists('frontendAudioForUrlApiV1FrontendAudioForUrlPost', 'url', url)
            const localVarPath = `/api/v1/frontend-audio-for-url`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (url !== undefined) {
                localVarQueryParameter['url'] = url;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Frontend Audio Play
         * @param {string} userId 
         * @param {string} audioId 
         * @param {number} durationSeconds 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        frontendAudioPlayApiV1FrontendAudioPlayPost: async (userId: string, audioId: string, durationSeconds: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('frontendAudioPlayApiV1FrontendAudioPlayPost', 'userId', userId)
            // verify required parameter 'audioId' is not null or undefined
            assertParamExists('frontendAudioPlayApiV1FrontendAudioPlayPost', 'audioId', audioId)
            // verify required parameter 'durationSeconds' is not null or undefined
            assertParamExists('frontendAudioPlayApiV1FrontendAudioPlayPost', 'durationSeconds', durationSeconds)
            const localVarPath = `/api/v1/frontend-audio-play`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }

            if (audioId !== undefined) {
                localVarQueryParameter['audio_id'] = audioId;
            }

            if (durationSeconds !== undefined) {
                localVarQueryParameter['duration_seconds'] = durationSeconds;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Frontend Audios Similar For Text
         * @param {string} text 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        frontendAudiosSimilarForTextApiV1FrontendAudioResultsSimilarForTextPost: async (text: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'text' is not null or undefined
            assertParamExists('frontendAudiosSimilarForTextApiV1FrontendAudioResultsSimilarForTextPost', 'text', text)
            const localVarPath = `/api/v1/frontend-audio-results-similar-for-text`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (text !== undefined) {
                localVarQueryParameter['text'] = text;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Frontend Audios Similar For Text
         * @param {string} text 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        frontendAudiosSimilarForTextApiV1FrontendAudiosSimilarForTextPost: async (text: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'text' is not null or undefined
            assertParamExists('frontendAudiosSimilarForTextApiV1FrontendAudiosSimilarForTextPost', 'text', text)
            const localVarPath = `/api/v1/frontend-audios-similar-for-text`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (text !== undefined) {
                localVarQueryParameter['text'] = text;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Basic health check endpoint
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckApiV1HealthGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Read Web Page Seeds
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readWebPageSeedsApiV1WebPageSeedsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/web-page-seeds`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Read Web Pages
         * @param {string} url 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readWebPagesApiV1WebPagesGet: async (url: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'url' is not null or undefined
            assertParamExists('readWebPagesApiV1WebPagesGet', 'url', url)
            const localVarPath = `/api/v1/web-pages`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (url !== undefined) {
                localVarQueryParameter['url'] = url;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Scraper Run
         * @param {ScraperRunRequest} scraperRunRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        scraperRunApiV1ScraperRunPost: async (scraperRunRequest: ScraperRunRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'scraperRunRequest' is not null or undefined
            assertParamExists('scraperRunApiV1ScraperRunPost', 'scraperRunRequest', scraperRunRequest)
            const localVarPath = `/api/v1/scraper-run`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(scraperRunRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Scraper Stop
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        scraperStopApiV1ScraperStopPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/scraper-stop`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Summarizer Run
         * @param {SummarizerRunRequest} summarizerRunRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        summarizerRunApiV1SummarizerRunPost: async (summarizerRunRequest: SummarizerRunRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'summarizerRunRequest' is not null or undefined
            assertParamExists('summarizerRunApiV1SummarizerRunPost', 'summarizerRunRequest', summarizerRunRequest)
            const localVarPath = `/api/v1/summarizer-run`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(summarizerRunRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Upsert Web Page Seed
         * @param {UpsertWebPageSeedRequest} upsertWebPageSeedRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        upsertWebPageSeedApiV1WebPageSeedsPost: async (upsertWebPageSeedRequest: UpsertWebPageSeedRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'upsertWebPageSeedRequest' is not null or undefined
            assertParamExists('upsertWebPageSeedApiV1WebPageSeedsPost', 'upsertWebPageSeedRequest', upsertWebPageSeedRequest)
            const localVarPath = `/api/v1/web-page-seeds`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(upsertWebPageSeedRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * Detailed health check endpoint
         * @summary Detailed Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async detailedHealthCheckApiV1HealthDetailedGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.detailedHealthCheckApiV1HealthDetailedGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.detailedHealthCheckApiV1HealthDetailedGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Frontend Audio For Url
         * @param {string} url 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async frontendAudioForUrlApiV1FrontendAudioForUrlPost(url: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FAFrontendAudio>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.frontendAudioForUrlApiV1FrontendAudioForUrlPost(url, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.frontendAudioForUrlApiV1FrontendAudioForUrlPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Frontend Audio Play
         * @param {string} userId 
         * @param {string} audioId 
         * @param {number} durationSeconds 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async frontendAudioPlayApiV1FrontendAudioPlayPost(userId: string, audioId: string, durationSeconds: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.frontendAudioPlayApiV1FrontendAudioPlayPost(userId, audioId, durationSeconds, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.frontendAudioPlayApiV1FrontendAudioPlayPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Frontend Audios Similar For Text
         * @param {string} text 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async frontendAudiosSimilarForTextApiV1FrontendAudioResultsSimilarForTextPost(text: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<FAFrontendAudioSearchResult>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.frontendAudiosSimilarForTextApiV1FrontendAudioResultsSimilarForTextPost(text, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.frontendAudiosSimilarForTextApiV1FrontendAudioResultsSimilarForTextPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Frontend Audios Similar For Text
         * @param {string} text 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async frontendAudiosSimilarForTextApiV1FrontendAudiosSimilarForTextPost(text: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<FAFrontendAudio>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.frontendAudiosSimilarForTextApiV1FrontendAudiosSimilarForTextPost(text, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.frontendAudiosSimilarForTextApiV1FrontendAudiosSimilarForTextPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Basic health check endpoint
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthCheckApiV1HealthGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthCheckApiV1HealthGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.healthCheckApiV1HealthGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Read Web Page Seeds
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async readWebPageSeedsApiV1WebPageSeedsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<FAWebPageSeed>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.readWebPageSeedsApiV1WebPageSeedsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.readWebPageSeedsApiV1WebPageSeedsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Read Web Pages
         * @param {string} url 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async readWebPagesApiV1WebPagesGet(url: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FAWebPage>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.readWebPagesApiV1WebPagesGet(url, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.readWebPagesApiV1WebPagesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Scraper Run
         * @param {ScraperRunRequest} scraperRunRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async scraperRunApiV1ScraperRunPost(scraperRunRequest: ScraperRunRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FAScraperStats>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.scraperRunApiV1ScraperRunPost(scraperRunRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.scraperRunApiV1ScraperRunPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Scraper Stop
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async scraperStopApiV1ScraperStopPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.scraperStopApiV1ScraperStopPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.scraperStopApiV1ScraperStopPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Summarizer Run
         * @param {SummarizerRunRequest} summarizerRunRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async summarizerRunApiV1SummarizerRunPost(summarizerRunRequest: SummarizerRunRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FAScraperStats>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.summarizerRunApiV1SummarizerRunPost(summarizerRunRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.summarizerRunApiV1SummarizerRunPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Upsert Web Page Seed
         * @param {UpsertWebPageSeedRequest} upsertWebPageSeedRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async upsertWebPageSeedApiV1WebPageSeedsPost(upsertWebPageSeedRequest: UpsertWebPageSeedRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.upsertWebPageSeedApiV1WebPageSeedsPost(upsertWebPageSeedRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.upsertWebPageSeedApiV1WebPageSeedsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * Detailed health check endpoint
         * @summary Detailed Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        detailedHealthCheckApiV1HealthDetailedGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.detailedHealthCheckApiV1HealthDetailedGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Frontend Audio For Url
         * @param {string} url 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        frontendAudioForUrlApiV1FrontendAudioForUrlPost(url: string, options?: RawAxiosRequestConfig): AxiosPromise<FAFrontendAudio> {
            return localVarFp.frontendAudioForUrlApiV1FrontendAudioForUrlPost(url, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Frontend Audio Play
         * @param {string} userId 
         * @param {string} audioId 
         * @param {number} durationSeconds 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        frontendAudioPlayApiV1FrontendAudioPlayPost(userId: string, audioId: string, durationSeconds: number, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.frontendAudioPlayApiV1FrontendAudioPlayPost(userId, audioId, durationSeconds, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Frontend Audios Similar For Text
         * @param {string} text 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        frontendAudiosSimilarForTextApiV1FrontendAudioResultsSimilarForTextPost(text: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<FAFrontendAudioSearchResult>> {
            return localVarFp.frontendAudiosSimilarForTextApiV1FrontendAudioResultsSimilarForTextPost(text, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Frontend Audios Similar For Text
         * @param {string} text 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        frontendAudiosSimilarForTextApiV1FrontendAudiosSimilarForTextPost(text: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<FAFrontendAudio>> {
            return localVarFp.frontendAudiosSimilarForTextApiV1FrontendAudiosSimilarForTextPost(text, options).then((request) => request(axios, basePath));
        },
        /**
         * Basic health check endpoint
         * @summary Health Check
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheckApiV1HealthGet(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.healthCheckApiV1HealthGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Read Web Page Seeds
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readWebPageSeedsApiV1WebPageSeedsGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<FAWebPageSeed>> {
            return localVarFp.readWebPageSeedsApiV1WebPageSeedsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Read Web Pages
         * @param {string} url 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readWebPagesApiV1WebPagesGet(url: string, options?: RawAxiosRequestConfig): AxiosPromise<FAWebPage> {
            return localVarFp.readWebPagesApiV1WebPagesGet(url, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Scraper Run
         * @param {ScraperRunRequest} scraperRunRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        scraperRunApiV1ScraperRunPost(scraperRunRequest: ScraperRunRequest, options?: RawAxiosRequestConfig): AxiosPromise<FAScraperStats> {
            return localVarFp.scraperRunApiV1ScraperRunPost(scraperRunRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Scraper Stop
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        scraperStopApiV1ScraperStopPost(options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.scraperStopApiV1ScraperStopPost(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Summarizer Run
         * @param {SummarizerRunRequest} summarizerRunRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        summarizerRunApiV1SummarizerRunPost(summarizerRunRequest: SummarizerRunRequest, options?: RawAxiosRequestConfig): AxiosPromise<FAScraperStats> {
            return localVarFp.summarizerRunApiV1SummarizerRunPost(summarizerRunRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Upsert Web Page Seed
         * @param {UpsertWebPageSeedRequest} upsertWebPageSeedRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        upsertWebPageSeedApiV1WebPageSeedsPost(upsertWebPageSeedRequest: UpsertWebPageSeedRequest, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.upsertWebPageSeedApiV1WebPageSeedsPost(upsertWebPageSeedRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * Detailed health check endpoint
     * @summary Detailed Health Check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public detailedHealthCheckApiV1HealthDetailedGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).detailedHealthCheckApiV1HealthDetailedGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Frontend Audio For Url
     * @param {string} url 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public frontendAudioForUrlApiV1FrontendAudioForUrlPost(url: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).frontendAudioForUrlApiV1FrontendAudioForUrlPost(url, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Frontend Audio Play
     * @param {string} userId 
     * @param {string} audioId 
     * @param {number} durationSeconds 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public frontendAudioPlayApiV1FrontendAudioPlayPost(userId: string, audioId: string, durationSeconds: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).frontendAudioPlayApiV1FrontendAudioPlayPost(userId, audioId, durationSeconds, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Frontend Audios Similar For Text
     * @param {string} text 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public frontendAudiosSimilarForTextApiV1FrontendAudioResultsSimilarForTextPost(text: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).frontendAudiosSimilarForTextApiV1FrontendAudioResultsSimilarForTextPost(text, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Frontend Audios Similar For Text
     * @param {string} text 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public frontendAudiosSimilarForTextApiV1FrontendAudiosSimilarForTextPost(text: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).frontendAudiosSimilarForTextApiV1FrontendAudiosSimilarForTextPost(text, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Basic health check endpoint
     * @summary Health Check
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public healthCheckApiV1HealthGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).healthCheckApiV1HealthGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Read Web Page Seeds
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public readWebPageSeedsApiV1WebPageSeedsGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).readWebPageSeedsApiV1WebPageSeedsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Read Web Pages
     * @param {string} url 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public readWebPagesApiV1WebPagesGet(url: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).readWebPagesApiV1WebPagesGet(url, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Scraper Run
     * @param {ScraperRunRequest} scraperRunRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public scraperRunApiV1ScraperRunPost(scraperRunRequest: ScraperRunRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).scraperRunApiV1ScraperRunPost(scraperRunRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Scraper Stop
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public scraperStopApiV1ScraperStopPost(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).scraperStopApiV1ScraperStopPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Summarizer Run
     * @param {SummarizerRunRequest} summarizerRunRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public summarizerRunApiV1SummarizerRunPost(summarizerRunRequest: SummarizerRunRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).summarizerRunApiV1SummarizerRunPost(summarizerRunRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Upsert Web Page Seed
     * @param {UpsertWebPageSeedRequest} upsertWebPageSeedRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public upsertWebPageSeedApiV1WebPageSeedsPost(upsertWebPageSeedRequest: UpsertWebPageSeedRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).upsertWebPageSeedApiV1WebPageSeedsPost(upsertWebPageSeedRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



