apiVersion: v1
kind: Service
metadata:
 name: postgres
spec:
 selector:
   app: postgres
 ports:
 - port: 5432
   targetPort: 5432
   nodePort: 30432  # Add this line - port range must be 30000-32767
 type: NodePort     # Change this line from ClusterIP
