apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: dXNlcg==      # 'user' in base64
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # 'password' in base64
  POSTGRES_DB: ZGI=        # 'db' in base64
