apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: ZGJfdXNlcg==      # 'db_user' in base64
  POSTGRES_PASSWORD: ZGJfcGFzc3dvcmQ=  # 'db_password' in base64
  POSTGRES_DB: ZGI=        # 'db' in base64
