# docker-compose.yml
services:
  pysrc:
    build:
      context: .
      dockerfile: pysrc/Dockerfile
    image: gcr.io/radiozilla-92c5f/radiozilla-pysrc:latest
  
  scraperjob:
    build:
      context: .
      dockerfile: publisherjob/Dockerfile
    image: gcr.io/radiozilla-92c5f/radiozilla-publisherjob:latest
    depends_on:
      - pysrc


  