apiVersion: batch/v1
kind: Job
metadata:
  generateName: ttsjob-  # This will append a unique suffix each time
  labels:
    app: ttsjob
    type: batch-process
spec:
  ttlSecondsAfterFinished: 600  # Keep jobs for 7 days
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: ttsjob
        type: batch-process
    spec:
      containers:
      - name: python-container
        image: localhost:32000/radiozilla-ttsjob:latest  # Replace with your image registry
        resources:
          requests:
            memory: "16Gi"
            cpu: "2000m"
          limits:
            memory: "16Gi"
            cpu: "2000m"
      restartPolicy: Never
