version: '3.8'

services:
  website:
    platform: linux/amd64
    build:
      context: ../
      dockerfile: website/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_URL=postgresql+asyncpg://db_user:db_password@host.docker.internal:5432/db
      - POSTGRES_URL=postgresql+asyncpg://db_user:db_password@host.docker.internal:5432/db
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - radiozilla-network
    image: gcr.io/radiozilla-92c5f/radiozilla-website:latest

networks:
  radiozilla-network:
    driver: bridge
